version: "3"
services:
  db:
    container_name: clickflow_timescale_db
    image: timescale/timescaledb:latest-pg11
    environment:
      POSTGRES_DB: playground_timescale_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/11
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data:
    driver: local
networks:
  default:
    external:
      name: clickflow_timescale_default
